### ISSUE TITLE
mobile with widescreen not displaying correctly

### ISSUE THREAD

**Issue by TimWillis** [PolymerElements/paper-scroll-header-panel#16]
Hi, I have a site at - https://crackling-heat-6713.firebaseapp.com/index.html#!/xmenu/home - that uses this, but when I view it on my htc m8 it looks good when viewing in portrait, but when I turn it to landscape, the background image and my title bleeds over into the content.

Thanks
Tim

**Comment by TimWillis** [comment]
Noticed in ff mobile.

**Comment by TimWillis** [comment]
same in chrome too.

**Comment by frankiefu** [comment]
Confirmed it is a bug.  Can also reproduce it using the paper-scroll-header-panel's demo by resizing the browser from wide to narrow, then scroll the page to get to condensed toolbar and you would see the title and the button are not aligned correctly.

![screen shot 2015-06-18 at 7 03 55 pm](https://cloud.githubusercontent.com/assets/116360/8246059/cfff9a52-15ec-11e5-8218-4df1eafc2e83.png)

This is happening because resize triggers `headerHeight` to change but `condensedHeaderHeight` is still using the old value.
