### ISSUE TITLE
Show the scrollbar above the header

### ISSUE THREAD

**Issue by infacq** [PolymerElements/paper-scroll-header-panel#28]
I want to have effect as in the official website. How can I make use using this element to produce such effect (shadow, when scroll). Because I hate to see if the header element is blocking the scrollbar when viewing on desktop browser. I want to have scrollbar appear all the time and have effect like this element

**Comment by bardak-dev** [comment]
I have a same question! this realy important, I already broke my head trying to do this.

**Comment by ebidel** [comment]
https://elements.polymer-project.org/elements/paper-header-panel?view=demo:demo/index.html has this behavior, although I think we may deprecate it and add its functionality to this element. cc @blasten

**Comment by blasten** [comment]
yeah. I had a brainstorming session with @frankiefu about this issue, because I agree that it's annoying. 
- `paper-header-panel` doesn't show the scrollbar above of the header element :(
- the Polymer website uses a custom thing that delegates the scroll to the document element. This approach would require to use `position:fixed` for menus, toolbars, and so on. And it would get even more complicated for single page apps.
- We thought about adding the header element to the content inside the scroll and then subtracting the `scrollTop` from the header's y position, but we will notice a lag since the scroll event isn't synced with what is rendered.

**Comment by bardak-dev** [comment]
@blasten But it somehow working well on: https://store.google.com/
maybe it doesn't polymer but still.

**Comment by infacq** [comment]
but that one, the shadow always appear. How about shadow appear when user interact with scroller only?

**Comment by bardak-dev** [comment]
@infacq Are you edited your topic issue? I thought we were talking about displaying scroll-header-panel on desktop. When header-panel gets on scroll line.
![0op4f4aj](https://cloud.githubusercontent.com/assets/5928632/8637253/b34ad01e-2890-11e5-89bf-7d7eb95295b6.png)

**Comment by blasten** [comment]
@bardak-dev yes that is the issue

**Comment by robrez** [comment]
:+1:

**Comment by deckar01** [comment]
> The fact that the scroll bar affects the toolbar implies that the toolbar should be on the parent panel. 

Discussion from #46

**Comment by blasten** [comment]
This issue is fixed in https://github.com/PolymerLabs/app-layout

**Comment by blasten** [comment]
I'd recommend trying out https://github.com/PolymerLabs/app-layout, This issue is fixed 🎉

**Comment by RhysyG** [comment]
Hey! In the PSK, why does the app-header-layout have has-scrolling-region by default? It seems to cause this issue too.

Thanks.

![screen shot 2016-09-28 at 10 27 36 am](https://cloud.githubusercontent.com/assets/5491092/18896613/6ce21ad6-8566-11e6-9efc-ab1276fb78c9.png)
