### ISSUE TITLE
Can't scroll over element

### ISSUE THREAD

**Issue by didrocks** [PolymerElements/paper-scroll-header-panel#46]
When we have a large height paper-scroll-header-panel, user may want to scroll the whole page over the element as well.

There was a workaround percing the shadow dom on core-scroll-header-panel (https://github.com/Polymer/core-scroll-header-panel/issues/1), however, this isn't possible with Polymer elements 1.0 anymore. Do you think this could and should be implemented elegantly (at least, scrolling on the background, not individual elements on top)?

**Comment by deckar01** [comment]
Setting `pointer-events: none;` on the toolbar will pass the scroll events to the underlying container element, but is not a complete solution due to it's children still capturing scroll events.

The fact that the scroll bar affects the toolbar implies that the toolbar should be on the parent panel. Solutions for #28 should take this issue into consideration.

**Comment by blasten** [comment]
@didrocks sorry for the late response. You are right, and we always want to do better even if there are some browser/perf limitations. For that reason we have a new experimental set of layout elements https://github.com/PolymerLabs/app-layout  that aim to solve this issue. This experimental set of elements will be soon released as carbon elements along with new elements for routing and internationalization. Check it out!

**Comment by didrocks** [comment]
@blasten: excellent, thanks! I'm giving it a look :)
